runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: home.app

- url: /gpu
  script: gpu.app

- url: /gpu/new
  script: gpu.app

- url: /gpu/update
  script: gpu.app

