runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: home.app

- url: /gpu
  script: gpu.app

- url: /gpu/new
  script: gpu.app

- url: /gpu/edit
  script: gpu.app

- url: /gpu/view
  script: gpu.app

- url: /gpu/search
  script: gpu.app

- url: /gpu/compare
  script: gpu.app

- url: /gpu/selection
  script: gpu.app

- url: /assets
  static_dir: assets
